sudo: required
services:
  - docker

before_install:
  - docker build -t wesleybasson/docker-course-project-alpha -f Dockerfile.dev .

script:
  - docker run -e CI=true wesleybasson/docker-course-project-alpha npm run test

language: generic

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-course-project-alpha"
  env: "Dockercourseprojectalpha-env"
  bucket_name: "elasticbeanstalk-us-east-1-009183221110"
  bucket_path: "docker-course-project-alpha"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY